bdash-app/bdash

README.md
https://github.com/bdash-app/bdash/pull/2 is not complete :bow:
=> Fix releases URL

app/main/index.js
On macOS, you close the main window once then cannot reopen the window even if click dock icon.
This fixes it.
=> Make it re-openable by clicking Dock icon on macOS

app/lib/DataSourceDefinition/Postgres.js, app/renderer/components/DataSourceForm/DataSourceForm.js
I use heroku that use postgresql SSL connection.
How is this?
=> Add SSL setting for Postgres

package.json, test/e2e/index.js, test/fixtures/mysql/initialize.js, test/fixtures/postgres/initialize.js, test/lib/DataSourceDefinition/Mysql.js, test/lib/DataSourceDefinition/Postgres.js, yarn.lock
Use [execa](https://github.com/sindresorhus/execa) and [fs-extra@^3 to use promisified APIs](https://github.com/jprichardson/node-fs-extra#sync-vs-async).
=> More async

app/lib/DataSourceDefinition/Base.js, app/lib/DataSourceDefinition/BigQuery.js, app/lib/DataSourceDefinition/Mysql.js, app/lib/DataSourceDefinition/Postgres.js, app/lib/DataSourceDefinition/TreasureData.js, app/lib/QuerySharing.js, app/renderer/pages/Query/Query.js
I'd like to also share data source information.
Shared data source looks like this https://gist.github.com/eagletmt/ccdd721ba4a4935ed848ea211a0f59b3
@hokaccha What do you think?
=> Add data source information file to shared query

package.json, yarn.lock
I just do `yarn remove react-micro-container` 😃
=> Remove unused react-micro-container

package.json
- Make it copyable on Linux #36 @pocke 
- Update react and react-dom for [CVE-2018-6341](https://nvd.nist.gov/vuln/detail/CVE-2018-6341)
=> Release v1.5.4

package.json
- Use title as file names to be shared on gist #38 @morishin
=> Release v1.5.5

src/renderer/components/Editor/Editor.tsx
=> Unmap `<C-c>` only once to fix crash in query page

src/main/menu.ts
https://electronjs.org/docs/api/menu#main-process
=> Restore "quit" menu item for non-darwin platforms

package.json, src/renderer/app.tsx, src/renderer/components/QueryHeader/QueryHeader.css, src/renderer/components/QueryHeader/QueryHeader.tsx, src/renderer/components/QueryResultChart/QueryResultChart.tsx, src/renderer/components/Select.ts, src/renderer/pages/Setting/Setting.css, src/renderer/pages/Setting/Setting.tsx, yarn.lock
- Update React-Select v3 https://react-select.com/home
- [Rename old props name](https://react-select.com/upgrade-guide)
- Fix styles (details below)
- Update React to 16.8 (react-select 3 depends on)
Default of v3 style is bad for me.
- Delete separator between label and clean button
- Color of item selected is very strong. I like v1 color (hover and selected)
- Delete margin between select and menu
=> Update React to 16.8 and React-Select to 3

src/main/index.ts, src/main/menu.ts, src/main/updater.ts
- Use await to handle promise objects
- Add types to sources of main process
=> Fix unhandled promises

src/lib/Database/Query.ts, src/lib/QuerySharing.ts, src/renderer/components/QueryEditor/QueryEditor.tsx, src/renderer/components/QueryHeader/QueryHeader.tsx, src/renderer/components/QueryList/QueryList.tsx, src/renderer/components/QueryResult/QueryResult.tsx, src/renderer/components/QueryResultChart/QueryResultChart.tsx, src/renderer/components/QueryResultNav/QueryResultNav.tsx, src/renderer/components/QueryResultTable/QueryResultTable.tsx, src/renderer/pages/Query/Query.tsx, src/renderer/pages/Query/QueryAction.ts, src/renderer/pages/Query/QueryStore.ts, test/unit/lib/Database/Query.test.ts
- Add context menu item to duplicate query
- Add QueryType
- Fix Query.body is always not undefined
=> Add feature to duplicate query

src/lib/QuerySharing.ts, src/renderer/pages/Query/Query.tsx
=> Fix gist sharing bug when chart is missing

src/renderer/components/QueryResultNav/QueryResultNav.css, src/renderer/pages/Query/Query.css
=> Fix position of query result nav bar

src/lib/Database/Query.ts, src/renderer/components/QueryEditor/QueryEditor.tsx, src/renderer/pages/Query/QueryAction.ts, test/unit/lib/Database/Query.test.ts
Display last executed time (local timezone)
=> Show executed time in the bottom of QueryEditor

src/lib/DataSource.ts, src/lib/DataSourceDefinition/Redshift.ts
Adds a Redshift data source for Spectrum support.
=> Add Redshift data source

src/main/index.ts, src/main/menu.ts, src/main/window.ts
Open multiple windows with `Window -> New Window` or `Ctrl or Cmd + Shfit + N` 
FYI @aamine
=> Make it possible to open multiple windows

test/integration/test.ts
=> Add integration test for changing query

test/integration/test.ts
Sometime #108 test becomes timeout failure
http://v4.webdriver.io/api/utility/waitUntil.html
=> Extend timeout of integration test to avoid test failure

src/renderer/components/Editor/Editor.tsx, src/renderer/components/QueryEditor/QueryEditor.tsx
Follow up https://github.com/bdash-app/bdash/pull/107
=> Do not trigger onChange event when query is selected

src/renderer/flux/Store.ts, src/renderer/pages/App/AppStore.ts, src/renderer/pages/DataSource/DataSourceStore.ts, src/renderer/pages/Query/QueryStore.ts, src/renderer/pages/Setting/SettingStore.ts, src/typings/immup.d.ts
- Fix types of Store class
- Add types to Immup
=> Fix type of Store

package.json, src/renderer/components/QueryEditor/QueryEditor.tsx, test/integration/test.ts, yarn.lock
CodeMirror editor needs refresh after click Query menu.
It causes with long query (about 11 lines or more).
related issue https://github.com/codemirror/CodeMirror/issues/2469
=> Enable auto refresh of query editor

src/renderer/components/DataSourceList/DataSourceList.css, src/renderer/components/QueryList/QueryList.css, src/renderer/components/TableList/TableList.css, src/renderer/components/TableList/TableList.tsx
Disable to select text in list of Query, DataSource and Table
=> Disable to select text in list

src/main/window.ts, src/renderer/components/GlobalMenu/GlobalMenu.css, src/renderer/components/GlobalMenu/GlobalMenu.tsx, src/renderer/pages/App/App.css, src/renderer/pages/App/App.tsx
We can drag window by dragging left edge (black menu)
https://www.electronjs.org/docs/api/frameless-window#alternatives-on-macos
=> Frameless window in macOS

src/lib/Util/findQueryByLine.ts
NOTE: We should use suitable sql mode of CodeMirror for query.
=> Refine #123

src/renderer/pages/DataSource/DataSource.tsx
Since #104, bdash can not save a new data source.
It is due to my PR.
=> Fix the bug user can not create new datasource

package.json, yarn.lock
=> Update plotly.js to 1.57.1

.github/workflows/test.yml, test/unit/lib/DataSourceDefinition/Mysql.test.ts, test/unit/lib/DataSourceDefinition/Postgres.test.ts
#154
There are differences between previous CI:
- This pull request contains CI script only (lint & test).
- The script to build application & publish should be in another action definition (ex: `.github/workflows/publish.yml` )
- Update Postgresql from v12 to v13 for integration test environment.
=> Add CI definition of GitHub actions

src/renderer/components/QueryResultNav/QueryResultNav.css, src/renderer/components/QueryResultTable/QueryResultTable.css
=> Fix position of header of query result table

src/renderer/components/QueryResult/QueryResult.css, src/renderer/components/QueryResultNav/QueryResultNav.css
Fix horizontal position of QueryResultNav.
=> Fix not to scroll table header horizontal

package.json
Fix bad argument which to fix in #164
=> Fix wrong argument since webpack 5

src/renderer/components/QueryResult/QueryResult.css, src/renderer/components/QueryResultNav/QueryResultNav.css
Reverts bdash-app/bdash#168
There is a bug that the Execute button is not displayed.
=> Revert "Fix not to scroll table header horizontal"

src/renderer/components/QueryEditor/QueryEditor.css, src/renderer/components/QueryResult/QueryResult.css, src/renderer/components/QueryResultNav/QueryResultNav.css
I don't know why it was working until now 😅
=> Fix a bug that Execute button is not displayed

.gitignore, src/renderer/components/Editor/Editor.tsx
By this PR, we can use auto completion for SQL keywords like `SELECT`, `FROM` and others.
=> Enable auto completion for SQL keywords

package.json, src/lib/Setting.ts, src/main/menu.ts, src/renderer/components/Editor/Editor.tsx, src/renderer/components/QueryEditor/QueryEditor.tsx, src/renderer/pages/Setting/Setting.tsx, yarn.lock
https://user-images.githubusercontent.com/39471/150641672-ef9c25d0-4063-4ece-b617-400b44b264b8.mov
=> Implement formatter

package.json
- Add copy as JSON
- Update sql-formatter
=> bump v1.14.3

src/renderer/components/DataSourceForm/DataSourceForm.tsx, src/renderer/components/DataSourceList/DataSourceList.tsx, src/renderer/components/QueryEditor/QueryEditor.tsx, src/renderer/components/QueryHeader/QueryHeader.tsx, src/renderer/components/QueryList/QueryList.tsx, src/renderer/components/QueryResult/QueryResult.tsx, src/renderer/components/QueryResultNav/QueryResultNav.tsx, src/renderer/components/TableList/TableList.tsx
I removed `render` functions that was added by #231 .
Please review this.
=> Remove unnecessary render functions

.github/workflows/test.yml
Skip jobs on linux until https://github.com/bdash-app/bdash/issues/257 is solved
=> Avoid running job on linux until getting-stuck problem is solved

src/renderer/components/QueryList/QueryList.css, src/renderer/components/QueryList/QueryList.tsx
Close #248 
Created working code of #248
@hokaccha @morishin 
Would you try this code?
And let me know what you think. (Whether valuable to merge or not)
=> Introduce filtering query list function

src/lib/Database/Query.ts, src/renderer/components/QueryList/QueryList.css, src/renderer/components/QueryList/QueryList.tsx, test/unit/lib/Database/Query.test.ts
I have changed the appearance of QueryList so that you can quickly find the query you are looking for.
- Show the first line of query body
- Show createdAt of query
- Update selection appearance
before | after 
---- | ----
=> Update QueryList appearance

README.md, scripts/release
- Use `gh` command instead of `hub` command
- Add description about how to release
=> Improve release script

.github/workflows/prepare_release.yml, .github/workflows/test.yml, package.json, src/lib/DataSourceDefinition/SQLite3.ts, yarn.lock
In order to update electron, I updated Node.js to v16 and also updated sqlite3 to latest.
=> Update Node.js and SQLite versions in package.json and workflows

electron-builder.yml, scripts/notarize.js
Make the binary for macOS as arm64 instead of x86.
=> Use universal binary for macOS
