bdash-app/bdash

app/lib/Setting.js

setting.yml should not be world-readable because it could contain GitHub
personal access token. It might be better if we use another file to
store credentials.

Create ~/.bdash/setting.yml with mode=0600

---

app/lib/Chart.js
package.json
yarn.lock

hoverlabel.namelength parameter was introduced in v1.29.0.
https://github.com/plotly/plotly.js/releases/tag/v1.29.0
```sql
select
t % 2 as c1
, t % 3 as c2
, count(1) as very_long_column_name
from generate_series(1, 10) as t
group by 1, 2
;
```

Do not trim hover labels

---

src/renderer/components/Editor/Editor.tsx

When I was selecting codes and then I pushed down Tab, code selection is replaced to softtab.
I expected to indent code selection that is CodeMirror default behavior. 
Original implementation see here: https://github.com/codemirror/CodeMirror/blob/ed8dfeb5e2ed25b5dd1f1eccc7b757ca6dbd118d/src/edit/commands.js#L106-L109
So, I changed this behavior. what do you think?
| before | after |
| --- | --- |
| ![20180904080124_img20180904-16-1y7uici](https://user-images.githubusercontent.com/6443461/45018183-702cc300-b064-11e8-87a7-7a94f603663b.gif) | ![20180904080254_img20180904-19-zm9ulc](https://user-images.githubusercontent.com/6443461/45018184-728f1d00-b064-11e8-806a-1fefb2fb2794.gif) |

Indent selection on default mode

---

src/renderer/components/Editor/Editor.tsx

Problem
===
Copying query to OS clipboard is impossible on Linux while using Vim keybind.
I guess it has the same problem on Windows, but I don't have Windows machine, so I'm not sure.
By the way, it works well on macOS :apple:
Cause
===
The Vim keybind overrides `<C-c>`. In Vim, `<C-c>` works as `<Esc>` almost, so CodeMirror maps `<C-c>` to `<Esc>`.
https://github.com/codemirror/CodeMirror/blob/be9d254ecc708563727d1f4198383af660b32080/keymap/vim.js#L62-L65
It conceals OS keybind, so Linux user cannot copy query.
Solution
===
Unmap `<C-c>` except darwin.
I think copying is more important than `<Esc>`.
Because we can use other keys to leave insert mode instead of `<C-c>`. For example, `<C-[>` and `<Esc>`. But we do not have any alternative keys for copying.
Personally I think Vimmer does …

Make it copyable on Linux

---

src/lib/QuerySharing.ts

All files are shared on gist with the same names. They are difficult to distinguish in the list.
Use `query.title` as a file names prefix.

Use title as file names to be shared on gist

---

src/main/menu.ts
src/renderer/components/Editor/Editor.tsx

We can use shortcut toggle comment(s) in Editor.
https://codemirror.net/doc/manual.html (Search this page with "toggleComment")
~Note: MenuItem "Toggle Comment" do nothing works.
I need to use ipcMain to main process communicate with render process, I give up because it is difficult.
https://electronjs.org/docs/api/ipc-main
https://github.com/electron/electron/blob/v2.0.0/docs/api/ipc-main.md
(If you have a certain plan to communicate between main/renderer processes, I can program it.)~

Add the feature to toggle comment by Cmd or Ctrl + /

---

src/lib/Chart.ts

A pie chart is usually clockwise.
But default direction of plotly.js is counter-clockwise.
https://plot.ly/javascript/reference/#pie-direction
I suggest Bdash use clockwise.

Change pie chart direction to clockwise

---

package.json
src/lib/DataSourceDefinition/Mysql.ts
test/unit/lib/DataSourceDefinition/Mysql.test.ts
test/unit/lib/DataSourceDefinition/Postgres.test.ts

Fix a bug which progress circle displayed externally when execute queries return empty fields in Mysql. (e.g. `update`, `delete`, etc…)
And I added an entry point to execute tests which require DB and also test cases in Mysql and Postgres.

Fix mysql query executor in no field result

---

src/lib/DataSourceDefinition/Athena.ts
src/lib/DataSourceDefinition/Base.ts
src/lib/DataSourceDefinition/BigQuery.ts
src/lib/DataSourceDefinition/Mysql.ts
src/lib/DataSourceDefinition/Postgres.ts
src/lib/DataSourceDefinition/SQLite3.ts
src/lib/DataSourceDefinition/TreasureData.ts
src/lib/Util/stripHeredoc.ts

Define return types for DataSources.
I plan to add typedef for charts, queries and React components (Props and State).

Add return type definitions to datasources

---

.circleci/config.yml

Setup `test:unit:remote` in CircleCI.
Sample https://circleci.com/gh/mtgto/bdash/2
I have not permission to use CircleCI as Pull Request CI, please configure after merge it.
Document for integration DB: https://circleci.com/docs/2.0/postgres-config/

Support CircleCI DB integrated test

---

.circleci/config.yml

https://circleci.com/gh/bdash-app/bdash/159
```console
/bin/bash: lsb_release: command not found
```
circleci/node:10-browsers doesn't install lsb_release now.

Fix CircleCI fail

---

src/renderer/components/GlobalMenu/GlobalMenu.css
src/renderer/components/QueryHeader/QueryHeader.css

Master (Electron 7) changes the height of menu items and editor header.
(menu item is not regular square. editor header overlaps editor.)
I don't know why it changes, maybe the difference of Chromium version.
I set the height of changed elements.

Fix height of menu items and header

---

webpack.config.js

Since updated to Electron 7, source map doesn't works.
(Source tab doesn't have any src files in Chromium devtools...)
Because `devtool: "sourcemap"` doesn't works in current Chromium.
https://github.com/webpack/webpack/issues/8506
https://bugs.chromium.org/p/chromium/issues/detail?id=919575
This problem remains unresolved.
To solve, use "eval-source-map".
It can compile fast.
https://webpack.js.org/configuration/devtool/
But it contains "webpack-inline:///..." (it is compiled code even if filename is "*.ts" or "*.tsx")
"tsx" loses color syntax, but we can debug like breakpoints.
Same users exist, but no answer.
https://github.com/electron/electron/issues/20504

Fix devtool config to enable source map

---

src/lib/Database/Connection.ts
src/lib/Database/schema.ts
src/renderer/app.tsx
test/helpers/DatabaseHelper.ts
test/unit/lib/Database/Connection.test.ts

- Use `user_version` in sqlite3 db to manage db schema version.
- On start up, migrate db if latest version is larger than current version.

Add the feature to simple DB migration

---

src/main/index.ts

For detail, see https://github.com/electron/electron/issues/13008#issuecomment-569363295
In short:
- devtools uses CodeMirror to enable color syntax of jsx files
- devtools loads CodeMirror modules from Google server on demands
- If URL scheme is "devtools://",  dynamic loading failed in Electron (maybe Electron's bug)
Until Electron fix this problem, we need to rewrite request.

Fix color syntax of tsx in devtools

---

src/main/index.ts

Fix CircleCI failed since #41
It seems happens only in linux.
tsc generate __importStar when source contains `import xx, { yy } from "zz"`.
if zz is electron, it cause app crashes in linux.
https://circleci.com/gh/mtgto/bdash/34

Fix crash in linux

---

src/lib/Chart.ts

Fix graph is corrupt since #76
- Use default width, height from default size of plotly.js
- Decode data URI (Plotly.toImage encode as data uri)

Fix graph of gist is not work

---

package.json
yarn.lock

sqlite3 v4.1.1 provides prebuild binary for Electron v7.1.
https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#411

Update sqlite3 to v4.1.1

---

package.json
src/lib/DataSource.ts
src/lib/DataSourceDefinition/Athena.ts
src/lib/DataSourceDefinition/Base.ts
src/lib/DataSourceDefinition/BigQuery.ts
src/lib/DataSourceDefinition/Mysql.ts
src/lib/DataSourceDefinition/Postgres.ts
src/lib/DataSourceDefinition/SQLite3.ts
src/lib/DataSourceDefinition/TreasureData.ts
src/lib/Database/Connection.ts
src/lib/Database/DataSource.ts
src/lib/Setting.ts
src/renderer/components/DataSourceForm/DataSourceForm.tsx
src/renderer/components/DataSourceList/DataSourceList.tsx
src/renderer/components/TableList/TableList.tsx
src/renderer/components/TableSummary/TableSummary.tsx
src/renderer/flux/Container.ts
src/renderer/flux/Store.ts
src/renderer/pages/DataSource/DataSource.tsx
src/renderer/pages/DataSource/DataSourceAction.ts
src/renderer/pages/DataSource/DataSourceStore.ts
src/renderer/pages/Query/Query.tsx
src/renderer/pages/Setting/SettingStore.ts
test/integration/test.ts
test/unit/lib/DataSourceDefinition/Mysql.test.ts
test/unit/lib/DataSourceDefinition/Postgres.test.ts
test/unit/lib/Database/Query.test.ts
yarn.lock

- New feature: Set default data source
- Enable in Right-click menu (Disable is not working)
- Add types for datasource
- Add `@types/sqlite3`
- Update prettier to handle [TS 3.7 optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)

Add feature: default datastore, add data source types

---

package.json

I finally found the reason why my `lint:prettier` found nothing, but CI finds prettier warning.

Fix lint:prettier in npm scripts

---

src/lib/Chart.ts

- Use responsive to auto resize chart
- When window size is changing, chart size also changes
- Reduce bottom margin of chart image (use automargin)
- Set max width of svg to 600
example: https://gist.github.com/mtgto/1bfa7fa49b5e9850dcd601082764cc80

Refactor chart view

---

src/lib/QuerySharing.ts

Fix #67
Example: https://gist.github.com/mtgto/ef67b1d65ef5406388df1e92bb822d4c

Fix the order of figures on gist

---

src/renderer/components/TableList/TableList.css
src/renderer/components/TableList/TableList.tsx

The font name was changed in FontAwesome 5, so it could not be displayed.
FYI @mtgto

Use <i> instead of pseudo element

---

src/renderer/components/QueryResultChart/QueryResultChart.tsx

Since #73, user cannot clear "Group By" selectbox.

Fix to enable to clear the value of group by

---

.yarnrc
package.json
webpack.config.js
yarn.lock

- Update Electron v7.1.2 -> v7.1.12
- Fix deprecated dist-url
- https://github.com/electron/electron/blob/master/docs/breaking-changes.md#node-headers-url

Update to Electron v7.1.12

---

electron-builder.yml
src/main/index.ts
src/main/updater.ts
webpack.config.js

- Show app update dialog
- Set Linux icon (AppImage and Dock)
- AppImage icon can be seen with [appimaged](https://github.com/AppImage/appimaged)
- https://github.com/electron-userland/electron-builder/issues/3599#issuecomment-454095484
- Dock icon is enabled when icon argument is set in createWindow
- Show update notification
I run with v1.5.1 to test updater.

Show update notify and dialog + Linux icons

---

src/renderer/pages/Query/Query.css

The cause is that the structure of the DOM changed when splitter-layout was introduced.
FYI @mtgto

Fix a bug data source could not be selected

---

electron-builder.yml
src/lib/Bdash.ts
webpack.config.js

- Stop to bundle large size npm packages
- `aws-sdk` (19MB)
- `@fortawesome/font-awesome-free` (16MB)
- Delete node-sqlite3's build files
In my macOS environment:
Bdash.app size is 261MB => 216MB

Reduce app size by reducing large npm packages

---

src/renderer/components/TableList/TableList.tsx

When typing in filter text field in table list, it causes warning in devtool console:
It happens when value of input tag is null or undefined.

Fix filter text field in tablelist is uncontrolled

---

src/renderer/components/QueryEditor/QueryEditor.tsx

When selected query is changed, old selected query body changes into new selected query.
This bug caused since #104

Hotfix: query broken when switch another query since #104

---

src/lib/Util/findQueryByLine.ts
test/unit/lib/Util/findQueryByLine.test.ts

Fix bug in #102
CodeMirrror treats both ";" and "," as `'punctuation`.
But #102 regards punctuation ";" only.
For example, this queries are valid.
```sql
select 1, 2;
select 3;
```
But wrong parser parses first line as "select 1,".

Fix Util/findQueryByLine splits at comma

---

src/renderer/styles/app.css

Bdash v1.7.2 under macOS Catalina (10.15) uses serif fonts.
This bug is based on Chromium v78.
https://bugs.chromium.org/p/chromium/issues/detail?id=1000542
We choose two ways:
- Use `Hiragino Sans` as fallback font (This PR's way)
- It causes changing the font in macOS Mojave (10.14)
- Upgrade Electron to v8.
- Electron v8 uses Chromium v80 https://github.com/electron/electron/releases/tag/v8.0.0

Use "Hiragino Sans" font for sans-serif fallback

---

src/renderer/components/DataSourceList/DataSourceList.css
src/renderer/components/DataSourceList/DataSourceList.tsx
src/renderer/components/QueryList/QueryList.css
src/renderer/components/QueryList/QueryList.tsx

In macOS, this PR adds draggable areas top item of Query list and top item of DataSource list.
cf. #115

Add draggable area in macOS

---

src/lib/DataSourceDefinition/Athena.ts
src/lib/DataSourceDefinition/Base.ts
src/lib/DataSourceDefinition/BigQuery.ts
src/lib/DataSourceDefinition/Mysql.ts
src/lib/DataSourceDefinition/Postgres.ts
src/lib/DataSourceDefinition/Redshift.ts
src/lib/DataSourceDefinition/SQLite3.ts
src/lib/DataSourceDefinition/TreasureData.ts
src/lib/Database/DataSource.ts
src/lib/Util/findQueryByLine.ts
src/renderer/components/DataSourceForm/DataSourceForm.tsx
src/renderer/components/QueryEditor/QueryEditor.tsx
src/renderer/pages/DataSource/DataSourceStore.ts
src/renderer/pages/Query/Query.tsx
src/renderer/pages/Query/QueryAction.ts
test/unit/lib/Database/DataSource.test.ts
test/unit/lib/Util/findQueryByLine.test.ts

To colorize, use specific MIME type of CodeMirror.
Example: `serial8` is keyword of PostgreSQL, but not keyword of SQLite3, MySQL.

Use mime type of CodeMirror

---

src/lib/Setting.ts
src/renderer/components/QueryEditor/QueryEditor.tsx
src/renderer/pages/Setting/Setting.tsx

closes #127 
Add checkbox config to enable/disable line wrapping of query editor. Default value is false.
Screenshots:

Add line wrapping setting

---

src/lib/DataSourceDefinition/Postgres.ts

pg_attrdef.adsrc has been removed in PostgreSQL 12.
https://www.postgresql.org/docs/12/release-12.html
pg_attdef.adbin is also available in 9.5, which is the oldest supported
version currently.
https://www.postgresql.org/docs/9.5/catalog-pg-attrdef.html
Resolves #131

Use pg_attrdef.adbin to get default value of columns

---

src/main/window.ts

This changes shows dialog when renderer is crashed (caused by OOM, etc.)
https://www.electronjs.org/docs/api/web-contents#event-crashed
We might say "You need to restart Bdash" by dialog.
(Screenshot says app window is dyed white)

show dialog when webView is crashed

---

src/lib/DataSourceDefinition/SQLite3.ts
test/fixtures/sqlite3/initialize.ts
test/unit/lib/DataSourceDefinition/Sqlite3.test.ts

TableSummary component says `Cannot read property 'map' of undefined` when sqlite3 database has no table.
To fix it, set correct response for empty result for sqlite3.
In addition, add unit test for sqlite3.

fix empty response of Sqlite3

---

src/lib/QuerySharing.ts
src/lib/Setting.ts
src/renderer/pages/Setting/Setting.css
src/renderer/pages/Setting/Setting.tsx

To protect from out of memory error, add limit the maximum number of lines for sharing the query to gist.
Default maximum number of rows is 10,000.
Screenshot

Set limit the maximum number of lines of gist

---

src/lib/Database/Query.ts
src/lib/Database/schema.ts
src/renderer/components/Editor/Editor.tsx
src/renderer/components/QueryEditor/QueryEditor.tsx
src/renderer/pages/Query/Query.tsx
src/renderer/pages/Query/QueryAction.ts
test/unit/lib/Database/Query.test.ts

- Add `codeMirrorHistory` column to DB `queries` table
- Store query editor history to query database
- Prevent undo clears editor
----
クエリ間・別ページに移動したときにもエディタの履歴 (undo / redo) が残せるようにしました。
- `queries` テーブルに `codeMirrorHistory` カラムを追加
- エディタの履歴が[CodeMirrorの履歴](https://codemirror.net/doc/manual.html#getHistory)で取れるので、それをJSONで保存します
- （クエリを切り替えたときなど）Undoするとクエリが空状態にまでなるのを防ぐようにしました

Add feature to save editor history for each queries

---

src/lib/GitHubApiClient.ts
src/lib/QuerySharing.ts
src/lib/Setting.ts
src/renderer/pages/Setting/Setting.tsx

closes #138
This pull request adds checkbox in Setting component to decide share gist in public or secret.
Default is `share gist in secret` (= same as current version).
Screenshot

Add checkbox to select share on gist in public or secret

---

src/renderer/components/Editor/Editor.tsx

This Pull Request fixes Ctrl-K / Ctrl-Y behaviors like macOS:
- Ctrl-K removes the text from the selected string or cursor to the end of the line.
- Ctrl-Y do nothing
After
- Ctrl-K cuts the text from the selected string or cursor to the end of the line.
- Ctrl-Y pastes from buffer from Ctrl-K.
The copied text is stored separately from the OS's standard clipboard.
I couldn't find a way to store it to macOS from JavaScript, so I used [Electron's clipboard feature](https://www.electronjs.org/docs/api/clipboard).
----
macOSでCtrl-K / Ctrl-YをOS標準ぽい挙動になるようにしました。
- Ctrl-K 選択された文字列もしくはカーソル位置から行末までを削除します。
- Ctrl-Y: 選択位置にCtrl-Kでカットした文字列をペーストします。
コピーした文字列はOS標準のクリップボードとは別に保存されます。
ただJavaScriptから保存する方法が見つからなかったのでElectronのclipboardを使いました。
https://www.electronjs.org/docs/api/clipboard#clipboardreadfindtex …

Change Ctrl-K and Ctrl-Y motions as macOS native

---

src/lib/DataSourceDefinition/SQLite3.ts
src/renderer/components/Editor/Editor.tsx
src/renderer/components/QueryEditor/QueryEditor.tsx
src/renderer/pages/DataSource/DataSourceAction.ts
src/renderer/pages/Query/Query.tsx
src/renderer/pages/Query/QueryAction.ts

Implement very simple auto suggest feature.
- After 400 msec from query changed, table names are suggested.
- You can change the selection of suggestions by Ctrl-n / Ctrl-p (emacs-like).
- You can close suggestions by ESC.
Limitation:
- Use only table name for suggestion.
- Doesn't consider the context of query.

Add simple auto completion for table name

---

.yarnrc
package.json
yarn.lock

node-sqlite3 v5.0.0+ adopt N-API instead of NAN
https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#500
https://github.com/mapbox/node-sqlite3/issues/830
I understand a bit about N-API, but I know it reduces time to compile sqlite3:
> Technically, with the new N-API support we should already be able to support electron 9.0.0 without adding it to our build matrix. (Same goes for any future Electron release, even 8.3 & 7.3, etc..)
https://github.com/mapbox/node-sqlite3/pull/1335#issuecomment-637539424

Update node-sqlite3 to v5.0.2 & avoid to compile while installing

---

src/renderer/pages/Query/QueryAction.ts

#143 adds table name autocompletion, but it increases a wait while app is initializing.
We should use lazy load (background loading table names from DataSource while user selects a query).
For now, I disable #143.

Disable to get all tables of all DataSources while app initializing

---

src/lib/Setting.ts
src/renderer/pages/Query/Query.tsx

`yaml.safeDump` throws an exception if the value is undefined 😰
```
> require('js-yaml').safeDump({ foo: undefined })
Uncaught:
YAMLException: unacceptable kind of an object to dump [object Undefined]
at writeNode (/Users/kazuhito-hokamura/local/src/github.com/bdash-app/bdash/node_modules/js-yaml/lib/js-yaml/dumper.js:748:13)
at writeBlockMapping (/Users/kazuhito-hokamura/local/src/github.com/bdash-app/bdash/node_modules/js-yaml/lib/js-yaml/dumper.js:627:10)
at writeNode (/Users/kazuhito-hokamura/local/src/github.com/bdash-app/bdash/node_modules/js-yaml/lib/js-yaml/dumper.js:720:9)
at dump (/Users/kazuhito-hokamura/local/src/github.com/bdash-app/bdash/node_modules/js-yaml/lib/js-yaml/dumper.js:809:7)
at Object.safeDump (/Users/kazuhito-hokamura/local/src/github.com/bdash-app/bdash/node_mod …
```

Fix yaml dump error

---

electron-builder.yml
src/main/menu.ts

This PR adds a common about menu to see installed version information.

Add about menu to Windows/Linux platform

---

src/lib/Chart.ts
src/lib/Database/Chart.ts
src/lib/Database/schema.ts
src/lib/QuerySharing.ts
src/renderer/components/QueryResultChart/QueryResultChart.css
src/renderer/components/QueryResultChart/QueryResultChart.tsx
test/unit/lib/Database/Chart.test.ts

This PR enables multiple fields to be selected for the group by option of the chart. 
Let ![](https://render.githubusercontent.com/render/math?math=a,%20b,%20...,%20n) be vectors representing the group by values. Then, a separate line is created for every item in the cartesian product of ![](https://render.githubusercontent.com/render/math?math=a,%20b,%20...,%20n), i.e.
where
such that the pair has at least one entry in `rows`.

Enable group by for multiple fields

---

src/lib/AthenaClient.ts

GetQueryResults API only returns up to 1000 rows. So pagination is
required to get more rows.
https://docs.aws.amazon.com/athena/latest/APIReference/API_GetQueryResults.html

Follow pagination of Athena query results

---

package.json
src/lib/AthenaClient.ts
yarn.lock

aws-sdk-js v3 has built-in support for async/await.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-athena/index.html
This PR should conflict with #204 😄

Migrate to aws-sdk v3

---

src/lib/QuerySharing.ts

Added chart information to query sharing parameters in order for bdash-server to use the same logic as in Bdash.app to draw a chart.
See also: https://github.com/bdash-app/bdash-server/pull/16

Send also chart information to bdash-server

---

package.json
src/lib/DataSource.ts
src/lib/DataSourceDefinition/Base.ts
src/lib/DataSourceDefinition/Timestream.ts
src/renderer/pages/DataSource/DataSourceStore.ts
yarn.lock

This PR adds a new data source Amazon Timestream.
https://aws.amazon.com/timestream/
Amazon Timestream is a serverless time series database service that supports Trino (Presto) query language.
https://docs.aws.amazon.com/timestream/latest/developerguide/reference.html
The screenshot below uses this sample app dataset and query.
https://github.com/awslabs/amazon-timestream-tools/tree/mainline/sample_apps_reinvent2021

Add Amazon Timestream data source

---

package.json
src/lib/DataSourceDefinition/Postgres.ts
yarn.lock

TLS certificate verification was skipped in pg 7.x but pg 8.x started to
default to rejectUnauthorized=true.
https://node-postgres.com/announcements#2020-02-25
This PR reverts TLS verification behavior back to Bdash < v1.12.0. MySQL
driver in Bdash also skips TLS verification if "SSL CA File" is not
specified.

postgres: Skip TLS certificate verification

---

.eslintrc.yml
package.json
src/renderer/components/Button/Button.tsx
src/renderer/components/DataSourceForm/DataSourceForm.tsx
src/renderer/components/DataSourceList/DataSourceList.tsx
src/renderer/components/GlobalMenu/GlobalMenu.tsx
src/renderer/components/LoadingIcon/LoadingIcon.tsx
src/renderer/components/ModalDialog/ModalDialog.tsx
src/renderer/components/QueryEditor/QueryEditor.tsx
src/renderer/components/QueryHeader/QueryHeader.tsx
src/renderer/components/QueryList/QueryList.tsx
src/renderer/components/QueryResult/QueryResult.tsx
src/renderer/components/QueryResultNav/QueryResultNav.tsx
src/renderer/components/TableList/TableList.tsx
src/renderer/components/TableSummary/TableSummary.tsx
src/renderer/pages/DataSource/DataSource.tsx
src/renderer/pages/Query/Query.tsx
yarn.lock

In order to make it easy to develop and maintain components.
The excluded components from this PR are subject to the following rules:
- it is wrapped by `Container.create()` method (this method does not support functional components)
- it has `componentDidMount()` method (rewriting this method with `useEffect` hook makes it hard to check diffs)
- it has `shouldComponentUpdate()` method (rewriting this method with the second parameter of `React.memo` makes it hard to check diffs)
I tried to reduce git diffs in order to make it easy to review.
Almost components has `render()` function at the last position. 
Usually, functional components returns JSX directly.
```jsx
const MyComponent = () => {
return <div />
}
```
Rewriting class components' `render()` method to functional components' …

Rewrite some class components to functional components

---

src/lib/BdashServerClient.ts
src/lib/Database/Query.ts
src/lib/Database/schema.ts
src/lib/QuerySharing.ts
src/main/window.ts
src/renderer/components/QueryResult/QueryResult.tsx
src/renderer/components/QueryResultNav/QueryResultNav.tsx
src/renderer/pages/Query/Query.tsx
src/renderer/pages/Query/QueryAction.ts
test/unit/lib/Database/Query.test.ts

https://github.com/bdash-app/bdash-server/issues/13 の対応で、Bdash Server にクエリをシェアした時にクエリ ID を DB に保存しておいて、再度シェアする際に上書きするか新規クエリとしてシェアするかを選択できるようにしました。
またシェア済みのクエリはシェアボタンの横に Bdash Server で開くボタンを表示するようにしました。

Feature to update a bdash server query

---

src/lib/DataSourceDefinition/TreasureData.ts
src/lib/Database/DataSource.ts

* The actual client is TDClient
* With the current code, it raises an error
* Change default query engine to presto
* Presto runs smaller latency. It's better choice for ad-hoc quries
* Use https as the transfer protocol
* Treasure Data disallows http connection now
* Add "endpoint" option for TreasureData
* Treasure Data provides on multiple regions

Fix Treasure Data Data Source

---

package.json
yarn.lock

Uset td-client-node v0.4.0.
https://www.npmjs.com/package/td/v/0.4.0
Though this PR include yarn.lock changes, my intention is just `yarn install`. Other side effects are not intentional and I can fix as maintainer's direction.

Use td 0.4.0

---

.gitignore
.prettierignore
src/renderer/app.tsx
src/renderer/pages/App/App.tsx
src/renderer/pages/App/AppAction.ts
src/renderer/pages/App/AppErrorBoundary.tsx
src/renderer/pages/App/AppStore.ts

`App` コンポーネントを関数コンポーネントに書き換えるにあたり、エラーハンドリングの実装のみ `AppErrorBoundary` コンポーネントへ移動しました。
また、 `.gitignore` と `.prettierignore` が既存の設定だと `src/renderer/pages/App` ディレクトリを無視していたので、ルートディレクトリのみ対象とするように変更しました。
レビューお願いします。

Add AppErrorBoundary component

---

src/lib/DataSourceDefinition/TreasureData.ts

Treasure Data data source has failed with empty rows like this:
After this patch, bdash shows same result as:

[TreasureData] fix: TreasureData data source failed with empty result

---

src/renderer/components/QueryList/QueryList.tsx
src/renderer/pages/Query/QueryAction.ts

https://github.com/bdash-app/bdash/pull/256 makes a bug. No data source is selected when user select a query from the list because of it.
That makes it get not only `id` and `title` but also **`body`** and `created_at` for showing the query list.
https://github.com/bdash-app/bdash/blob/b64eb494729b99454d671d4eec4d3234928ce1aa/src/lib/Database/Query.ts#L33-L34
But `selectQuery` does not refetch a query from DB when `body` is not empty. Therefore the properties of the selected query other than the above properties (id, title, body, created_at) does not appear in the query details screen.
https://github.com/bdash-app/bdash/blob/b64eb494729b99454d671d4eec4d3234928ce1aa/src/renderer/pages/Query/QueryAction.ts#L47-L55
Always refetch a query from DB when a user make actions (select, duplicate) …

Load a query from DB whenever select or duplicate it

---

src/lib/Database/Query.ts

I have fixed an issue where the `body` field was not being duplicated when the query was duplicated.

Fix duplicating queries

---

package.json
webpack.config.js
yarn.lock

Webpack 5 uses `md4` hash function as default, but OpenSSL 3 doesn't support the legacy hash function and results in ERR_OSSL_EVP_UNSUPPORTED error.
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:130:10)
at BulkUpdateDecorator.hashFactory (/build/bdash/src/bdash-1.16.2/node_modules/webpack/lib/util/createHash.js:144:18)
at BulkUpdateDecorator.update (/build/bdash/src/bdash-1.16.2/node_modules/webpack/lib/util/createHash.js:46:50)
at RawSource.updateHash (/build/bdash/src/bdash-1.16.2/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
at NormalModule._initBuildHash (/build/bdash/src/bdash-1.16.2/node_modules/webpack/lib/NormalModule.js:838:17)
at handleParseResult …
```

Use xxhash64 hash function to fix OpenSSL 3 error

---

package.json

https://volta.sh
I added `volta` option into package.json to fix node and yarn versions by following these codes.
https://github.com/bdash-app/bdash/blob/b3d9db5f987557cc2d214c3e8ba18b2c2c17d6b1/.github/workflows/prepare_release.yml#L22
https://github.com/bdash-app/bdash/blob/b3d9db5f987557cc2d214c3e8ba18b2c2c17d6b1/.github/workflows/test.yml#L24
https://github.com/bdash-app/bdash/blob/b3d9db5f987557cc2d214c3e8ba18b2c2c17d6b1/yarn.lock#L2

Use volta to fix node and yarn versions

---

package.json
src/lib/Bdash.ts
src/main/Config.ts
src/main/window.ts
src/renderer/components/DataSourceList/DataSourceList.tsx
src/renderer/components/QueryList/QueryList.tsx
yarn.lock

`remote` module is removed from electron v14.
https://www.electronjs.org/blog/electron-14-0#removed-remote-module
I updated the codes that utilizes `remote` module and set `enableRemoteModule` to `false`.

Set enableRemoteModule to false

---

electron-builder.yml
scripts/notarize.js

Reverts bdash-app/bdash#272
It has been crashed. I will revert it...

Revert "Use universal binary for macOS"

---

src/renderer/components/QueryHeader/QueryHeader.css
src/renderer/components/QueryHeader/QueryHeader.tsx
src/renderer/components/QueryHeaderTitle/QueryHeaderTitle.css
src/renderer/components/QueryHeaderTitle/QueryHeaderTitle.tsx
src/renderer/components/QueryHeaderTitle/index.ts

This is a working code for https://github.com/bdash-app/bdash/issues/274
With this implementation, query title will behave like this:
https://github.com/user-attachments/assets/a9942248-7b22-40a9-b4b7-2d90d837b71d

Use textarea for query header to make it easier to editing long title

---

src/lib/Setting.ts
src/main/window.ts
src/renderer/pages/Query/QueryAction.ts
src/renderer/pages/Setting/Setting.tsx

- Add a notification setting for controlling:
- enable / disable notification
- what condition the notification will be send.
About the condition for sending notifications, I prepared following:
- `focusing`:  Send notification when the bdash window is focused.
- `not focusing`: Opposite of `focusing`. Send notification when the bdash window is **NOT** focused (default).
- `always`: Send notification regardless of focusing

Add notify setting
